version: '3.7'
    
services:
  web:
    build: ./aiohttp
    command: gunicorn --chdir generated openapi_server.app_factory:app_factory --bind 0.0.0.0:8000 --worker-class aiohttp.GunicornWebWorker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - 8000
    env_file:
      - ./.env.prod
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: