openapi: 3.0.0
info:
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/)
    or HTML.
  title: Sample API
  version: 0.1.9
servers:
- description: Optional server description, e.g. Main (production) server
  url: http://api.example.com/api
paths:
  /ping:
    get:
      operationId: ping
      responses:
        "200":
          description: OK
      tags:
      - ping
      x-openapi-router-controller: openapi_server.controllers.ping_controller
  /v1/users:
    post:
      description: Optional extended description in CommonMark or HTML.
      operationId: create_users
      requestBody:
        $ref: '#/components/requestBodies/UsersRequest'
        content:
          application/json:
            schema:
              example:
                username: username
              properties:
                username:
                  title: username
                  type: string
              title: UsersRequest
              type: object
        required: true
        x-body-name: body
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsersResponse'
          description: A JSON array of user names
      summary: Returns a list of users.
      tags:
      - create_users
      x-openapi-router-controller: openapi_server.controllers.create_users_controller
      x-codegen-request-body-name: body
components:
  requestBodies:
    UsersRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UsersRequest'
      required: true
  schemas:
    UserName:
      title: username
      type: string
    UsersRequest:
      example:
        username: username
      properties:
        username:
          title: username
          type: string
      title: UsersRequest
      type: object
    UsersResponse:
      example:
        name: name
      properties:
        name:
          title: name
          type: string
      required:
      - name
      title: UsersResponse
      type: object
